### ISSUE TITLE
Crash on mod loading

### ISSUE THREAD

**Issue by watermelon0guy** [cakeGit/Pattern-Schematics#2]
[crash-2024-07-30_10.49.05-client.txt](https://github.com/user-attachments/files/16424096/crash-2024-07-30_10.49.05-client.txt)
Without mod everything load fine. I was thinking this is some incopat with sinytra + owo lib, but when i remove owo, issue still persist
[crash-2024-07-30_10.54.12-client.txt](https://github.com/user-attachments/files/16424185/crash-2024-07-30_10.54.12-client.txt)
I'll be happy provide any info about problem to help

**Comment by cakeGit** [comment]
Looking at the logs there doesen't seem to be any mention of this mod, the actual error it self is `Caused by: java.io.FileNotFoundException: owo:shaders/core/spectrum.json`, and also the mod itself does not have a GameRenderer mixin as the error seems to be talking about.

![image](https://github.com/user-attachments/assets/e0fc6a40-d601-4ce8-b688-6f4c719a83a6)
The mod does load with just these installed, what mods are you using that depend on Owo lib?

**Comment by watermelon0guy** [comment]
I use Particular. I turn off it and it's dependencies (owo lib and sushi lib) and get second crash log

**Comment by cakeGit** [comment]
Ah ok, and the second one is `Caused by: net.minecraft.server.ChainedJsonException: Invalid shaders/core/createbigcannons_cannon_smoke_particle.json: File not found`, but you say that it is only when this mod is active?

**Comment by cakeGit** [comment]
I think i may have a fix, before I publish it can you just try this version to check that's your error? https://github.com/cakeGit/Pattern-Schematics/blob/main/create_pattern_schematics-1.0.2.jar (Edit : Fixed table)

Also if not please could you provide a log? Mc is weird sometimes so I was able to recreate it on my end and the error was only in the log not crash

**Comment by cakeGit** [comment]
~~This version does end up breaking the schematic table quick move, so just to check if it boots for now~~  Edit : Fixed table, download link is updated

**Comment by watermelon0guy** [comment]
Thanks for fast fix!
Works now
